# Generated by Django 3.2 on 2022-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0004_auto_20220523_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatus',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('pause', 'pause')], max_length=15, unique=True),
        ),
    ]
